### ISSUE TITLE
Overlaps with negative values

### ISSUE THREAD

**Issue by varsh1090** [zhoulab/bedvenn#2]
1. HC_modERN_venn.png in HPC folder - /ufrc/zhou/share/projects/P53_genomics/ChIPSeq/dm6analysis/peaks/dm6_bedpeaks/ValidSamples shows negative values for some overlaps. Could this be due to the order of files used for bed intersect?
2. Could we remove the extension ".bed" from the labels for the Venns to make the names more compact?

**Comment by victorlin** [comment]
Fixed negative values by first merging the original files. Additionally,

1. Do you still want the intersect file saved as a separate BED file?
2. Sometimes the venn diagram proportions of the venn diagram do not allow for a nice visual placement of the numbers and labels. Would you want the script to output something like:

        file1 only: <# BP>
        file2 only: <# BP>
        file3 only: <# BP>
        file12 only: <# BP>
        ...
        file123 only: <# BP>

If so, you can open another issue for these features.
